version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ..
      dockerfile: ./php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - mysql-phpmyadmin
    volumes:
      - ./../:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./../:/var/www:rw
    networks:
      - mysql-phpmyadmin
    depends_on:
      - php-fpm


  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "PMA_HOST=mysql"
      - "PMA_USER=${MYSQL_USER}"
      - "PMA_PASSWORD=${MYSQL_PASSWORD}"
    networks:
      - mysql-phpmyadmin


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: mysql
    restart: always
    networks:
      - mysql-phpmyadmin
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

networks:
  mysql-phpmyadmin:
volumes:
  mysql: